language: objective-c
before_install:
- gem install cocoapods
- cd Example
- pod install
script:
- xctool test -workspace HardCoreData.xcworkspace -scheme HardCoreData-Example -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
notifications:
  email:
    recipients:
    - krivoblotsky@me.com
    on_success: change
    on_failure: always